import { describe, expect, it } from "vitest";
// Read as text, not as types: these tests assert things about the *file*.
// `?raw` keeps this a browser-shaped import, so no @types/node is needed.
import ENDPOINTS from "./endpoints.ts?raw";
import SCHEMA from "./schema.d.ts?raw";
import { API_BASE } from "./client";

/**
 * Guards on the generated OpenAPI types (`npm run types` → `schema.d.ts`).
 *
 * What these CANNOT do: prove the committed file still matches what the live
 * API would produce. That needs the API running, which a unit test must not
 * require — see `schema drift` in the README/CI notes: the byte-level check is
 * `npm run types && git diff --exit-code src/api/schema.d.ts` against a booted
 * API, and belongs in the workflow that already starts one.
 *
 * What they CAN do, offline: catch the file being hand-edited, and catch the
 * frontend calling a path the committed document does not describe — the
 * failure `tsc` misses, because the URL strings in `endpoints.ts` are plain
 * strings, not keys of `paths`.
 */

/** `"/api/v1/findings/{finding_key}"` → `/findings/{}`. */
function schemaPaths(source: string): Set<string> {
  const block = source.slice(source.indexOf("export interface paths"), source.indexOf("export type webhooks"));
  const found = new Set<string>();
  for (const match of block.matchAll(/^ {4}"(\/[^"]*)":/gm)) {
    const path = match[1] as string;
    if (!path.startsWith(API_BASE)) continue;
    found.add(path.slice(API_BASE.length).replace(/\{[^}]+\}/g, "{}"));
  }
  return found;
}

/** The block of `operations` describing one operation id, on its own. */
function operationBlock(source: string, operationId: string): string {
  const operations = source.slice(source.indexOf("export interface operations"));
  const start = operations.indexOf(`    ${operationId}: {\n`);
  expect(start).toBeGreaterThan(-1);
  const rest = operations.slice(start + operationId.length + 8);
  const next = rest.search(/^ {4}[A-Za-z_][\w]*: \{$/m);
  return next === -1 ? rest : rest.slice(0, next);
}

/** Every literal the client is asked to fetch, with interpolations blanked. */
function requestedPaths(source: string): string[] {
  const found = new Set<string>();
  for (const match of source.matchAll(/(?:api|apiFile)<[^>]*>\(\s*([`"])([^`"]*)\1/g)) {
    found.add((match[2] as string).replace(/\$\{[^}]*\}/g, "{}"));
  }
  // The export paths are looked up from a record rather than passed inline.
  for (const match of source.matchAll(/^\s*(?:csv|pdf|json):\s*"([^"]+)",$/gm)) found.add(match[1] as string);
  return [...found];
}

describe("generated API schema", () => {
  it("is still a generated file, not one someone edited by hand", () => {
    expect(SCHEMA.startsWith("/**\n * This file was auto-generated by openapi-typescript.")).toBe(true);
    expect(SCHEMA).toContain("Do not make direct changes to the file.");
  });

  it("carries no `any` and no suppression comment (CLAUDE.md, frontend conventions)", () => {
    expect(SCHEMA).not.toMatch(/@ts-(ignore|expect-error|nocheck)/);
    expect(SCHEMA).not.toMatch(/\bany\b(?!-)/);
  });

  it("describes every path the client actually requests", () => {
    const described = schemaPaths(SCHEMA);
    const requested = requestedPaths(ENDPOINTS);

    // Sanity: the extraction found the calls, so an empty list can never pass.
    expect(requested.length).toBeGreaterThan(20);
    expect(described.size).toBeGreaterThan(20);

    expect(requested.filter((path) => !described.has(path))).toEqual([]);
  });

  it("still describes the viewer-gated dependency probe with its problem+json errors", () => {
    // The drift this file was last regenerated for: /health/deps became
    // viewer-gated, so the document grew 401 and 403 responses that the
    // committed types lacked for a while (SPEC §13, §15.1).
    const health = operationBlock(SCHEMA, "health_deps");
    expect(health).toContain("application/problem+json");
    expect(health).toMatch(/401: \{/);
    expect(health).toMatch(/403: \{/);
    // ...and the ungated liveness probe next to it still has neither.
    expect(operationBlock(SCHEMA, "health")).not.toMatch(/40[13]: \{/);
  });
});
